# Generated by Django 5.1.6 on 2025-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
