# Generated by Django 5.1.6 on 2025-02-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_city_student_address_student_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Class',
            new_name='student_class',
        ),
    ]
