# Generated by Django 5.1.6 on 2025-02-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_options_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DSA', models.FloatField()),
                ('Java', models.FloatField()),
                ('Prob_and_Stats', models.FloatField()),
                ('Web_technology', models.FloatField()),
                ('Sad', models.FloatField()),
                ('total', models.FloatField()),
                ('percentage', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
    ]
