# Generated by Django 5.1.6 on 2025-02-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_studentmarks_options_remove_studentmarks_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='Sad',
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='DSA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='Java',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='Prob_and_Stats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='Web_technology',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='percentage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.student'),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='SAD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
