# Generated by Django 5.1.6 on 2025-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='student_class',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='studentmarks',
            unique_together={('student', 'student_class')},
        ),
    ]
