# Generated by Django 5.1.6 on 2025-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_studentmarks_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='student_class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
